#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    wakkerbier-lf-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^wakkerbier-lf\.ddev\.site$`)
      
      service: "wakkerbier-lf-web-80"
      tls: false
      # middlewares:
      #   - "wakkerbier-lf-redirectHttps"
    wakkerbier-lf-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^wakkerbier-lf\.ddev\.site$`)
      
      service: "wakkerbier-lf-web-8025"
      tls: false
      # middlewares:
      #   - "wakkerbier-lf-redirectHttps"
    wakkerbier-lf-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^wakkerbier-lf\.ddev\.site$`)
      
      service: "wakkerbier-lf-xhgui-80"
      tls: false
      # middlewares:
      #   - "wakkerbier-lf-redirectHttps"
    
    
    
    wakkerbier-lf-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^wakkerbier-lf\.ddev\.site$`)
      
      service: "wakkerbier-lf-web-80"
      
      tls: true
      
    wakkerbier-lf-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^wakkerbier-lf\.ddev\.site$`)
      
      service: "wakkerbier-lf-web-8025"
      
      tls: true
      
    
    wakkerbier-lf-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^wakkerbier-lf\.ddev\.site$`)
      
      service: "wakkerbier-lf-xhgui-80"
      
      tls: true
      
    

  middlewares:
    wakkerbier-lf-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    wakkerbier-lf-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-wakkerbier-lf-web:80
        
    wakkerbier-lf-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-wakkerbier-lf-web:8025
        
    
    
    wakkerbier-lf-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-wakkerbier-lf-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/wakkerbier-lf.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/wakkerbier-lf.key